---
name: Run tests

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  pytest:
    uses: taughz/colcon-ci/.github/workflows/pytest.yaml@main
    with:
      strategy-os: |
        macos-latest
        ubuntu-22.04
      strategy-python: |
        3.10
        3.11
        3.12
      strategy-include-py36: false
      strategy-include-stdeb: false
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yamllint -f github .
  integration-tests:
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-core
    defaults:
      run:
        shell: bash
    steps:
      - name: Fix Home Directory
        run: |
          # Not sure why GitHub is messing with this
          echo "HOME=/root" >> $GITHUB_ENV
      - name: Setup Environment
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
              git \
              python-is-python3 \
              python3-pip \
              python3-venv
          pip install prysk
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Run integration tests
        run: |
          . /opt/ros/*/setup.bash
          prysk test/integration/*.t
